apiVersion: v1
kind: Secret
metadata:
  name: aws-secrect
  labels:
    app: udagram
data:
  credentials: W2RlZmF1bHRdDQphd3NfYWNjZXNzX2tleV9pZCA9IEFLSUE0QU40MkJKQ0VBMkdURkhDDQphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSB3ZEpIUlJkK1JMNEpKaitWc09Vd2FUWDNTZ09OV21uMVVBcGxHU3BTDQo=

