apiVersion: v1
kind: Secret
metadata:
  name: aws-secrect
  labels:
    app: udagram
data:
  aws_access_key_id: AKIA4AN42BJCKCKJGSLQ
  aws_secret_access_key: WlNubFBTdlMwNGlGMXcxSzhGQVZwNlpHNkJjMXMwWUtPNGVhNHdUTg==