apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: backend-user
        image: tamhv/udagram-api-user:v5
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:  { name: env-configmap }
