apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: backend-feed
          image: tamhv/udagram-api-feed:v5
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:  { name: env-configmap }
